// Generated by web_artifact_build from server/src/privileged.ts. Do not edit.
import { definePrivilegedContracts, z } from "@hatch/space-sdk";

export const privileged = definePrivilegedContracts({
  readJournal: {
    request: z.object({}),
    response: z.object({
      entries: z.array(
        z.object({
          severity: z.enum(["action", "warn", "info"]),
          text: z.string(),
        }),
      ),
      source: z.string(),
    }),
    timeoutMs: 10000,
  },
});
